### ISSUE TITLE
Support addressing classified Jar via coordinates

### ISSUE THREAD

**Issue by jjohannes** [gradlex-org/extra-java-module-info#130]
For example, to patch `io.netty:netty-transport-native-epoll` with classifier `linux-x86_64` you have to use the file name:

```
module("netty-transport-native-epoll-4.1.87.Final-linux-x86_64.jar", "io.netty.transport.epoll.linux.x86_64")
```

It should be possible to do it like this:

```
module("io.netty:netty-transport-native-epoll|linux-x86_64", "io.netty.transport.epoll.linux.x86_64")
```

**Comment by Vampire** [comment]
> It should be possible to do it like this:

Don't forget a version for version-catalog accessor usage :-)
Maybe a viable alternative: `module("io.netty:netty-transport-native-epoll", "io.netty.transport.epoll.linux.x86_64") { classifier = "linux-x86_64" }` or something like that.

**Comment by jjohannes** [comment]
The feature is implemented with the notation proposed in the description. Follwoing the same "identifier" notation used in [java-module-dependencies](https://github.com/gradlex-org/java-module-dependencies?tab=readme-ov-file#add-module-name-mapping-information-if-needed).

Generally, I would agree that we do to much "special" strings instead of a nicer DSL. For now, I want to stay consistent with things we already have in this and the other GradleX Modules Plugins.

Maybe something to revisit if we should do a 2.x with a reworked DSL.
