### ISSUE TITLE
About plain library but with MANIFEST.MF and Automatic-Module-Name

### ISSUE THREAD

**Issue by IThinkIGottaGo** [gradlex-org/extra-java-module-info#35]
Hello, I find some library like `org.http4k:http4k-serverless-alibaba::4.28.1.0` is a plain jar library, but it actually has `Automatic-Module-Name` field in its `META-INF/MANIFEST.MF` file.

But plugin for now seems can not auto recognize this jar as an automatic module.  I have to repeat the same `Automatic-Module-Name` value in the `extraJavaModuleInfo` block of my `build.gradle.kts` file, or else my IDE cannot add that library to `External Libraries` lists, and gradle said `Not a module and no mapping defined: xxxxx.jar` when build the code.

Could you consider make the plugin could auto treat the jar like this be an automatic module? Thanks~

**Comment by jjohannes** [comment]
Hi @IThinkIGottaGo. Ich checked the Jar at https://repo1.maven.org/maven2/org/http4k/http4k-serverless-alibaba/4.28.1.0/http4k-serverless-alibaba-4.28.1.0.jar

It does **not** have a `Automatic-Module-Name` in its `MANIFEST.MF`. This is the whole manifest file content:

```
Manifest-Version: 1.0
http4k_version: 4.28.1.0

```

**Comment by IThinkIGottaGo** [comment]
@jjohannes 
Oh, that's right. It's my misunderstand. Sorry~
So, actually what i see in my IDE, it is the 'magic' result from this plugin, when i configure it in `extraJavaModuleInfo` block (with `automaticModule`), the plugin will auto add `Automatic-Module-Name` into this module's `MANIFEST.MF` file. Is that how this plugin works?

**Comment by jjohannes** [comment]
No problem. Yes - the magic is that the plugin uses Gradle's [Artifact Transform](https://docs.gradle.org/current/userguide/artifact_transforms.html) feature. The Jars are transformed after they have been downloaded but **before** they are put on the Classpath/ModulePath. For the IDE, the transformed Jars are the ones it gets and shows (the ones that are really used in the end). 

The plugin appends a `-module` to the Jar's name. That's how you can usually spot the transformed ones in the IDE view.

**Comment by IThinkIGottaGo** [comment]
I got it. Thanks a lot~👍
