### ISSUE TITLE
Gradle catalog compatibility

### ISSUE THREAD

**Issue by elect86** [gradlex-org/extra-java-module-info#41]
Hello,

nice lib! 

Anyway, I'd love this to work with the Gradle Catalog feature, ie:

```
extraJavaModuleInfo {
    module(libs.therapi) {
        exportAllPackages()
    }
}
```

All the traditional args should be easily reachable from that handle..

**Comment by jjohannes** [comment]
Thanks for the suggestion.

A complete example would have to look like the following though. The _module name_ is still required as argument:


```
extraJavaModuleInfo {
    module(libs.therapi, "com.example.therapi.modulename") {
        exportAllPackages()
    }
}
```

In any case, the Catalog can be used right now. The syntax just doesn't look that "nice". But I don't think there is any other drawback. You can do this right now:

```
extraJavaModuleInfo {
    module(libs.therapi.get().module.toString(), "com.example.therapi.modulename") {
        exportAllPackages()
    }
}
```
I think supporting the Catalog types in the API directly could be a nice addition and a PR is welcome!
