### ISSUE TITLE
Plugin hides automatic modules that do not show configuration, regardless of the presence of Automatic-Module-Name

### ISSUE THREAD

**Issue by syrm-ll** [gradlex-org/extra-java-module-info#48]
Plugin hides automatic modules that do not show configuration, regardless of the presence of Automatic-Module-Name

I'm not sure if this is intentional, it feels a bit out of place, at least modules that explicitly provide an `Automatic-Module-Name` should not be hidden

example:
![图片](https://user-images.githubusercontent.com/40515646/236706411-b0fb8b24-1eca-4f99-8199-226d907c6cfe.png)
`org.jetbrains.kotlin:kotlin-stdlib:1.8.21`

```kts
// build.gradle.kts

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.8.21")
}
```
Ignoring `kotlin-stdlib-common` and `jetbrains:annotations` which should be passed

The following configuration must be provided in order to transfer dependencies normally:
```kts
// build.gradle.kts

extraJavaModuleInfo {
    automaticModule("kotlin-stdlib-common-1.8.21.jar", "kotlin.stdlib.common")
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.8.21")
}
```

**Comment by jjohannes** [comment]
@syrm-ll I am not sure I completely understand the issue.

If you have a Jar without `module-info.class` and without  `Automatic-Module-Name` it is **not** considered a Module by Gradle. This is Gradle core behavior and nothing this plugin influences.

`kotlin-stdlib-common-1.8.21.jar` does **not** have a `module-info.class` or an  `Automatic-Module-Name`.
See: https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.21

That's why you need to do something like:
```
extraJavaModuleInfo {
    automaticModule("kotlin-stdlib-common-1.8.21.jar", "kotlin.stdlib.common")
}
```

Or you can do:
```
extraJavaModuleInfo {
    failOnMissingModuleInfo.set(false)
}
```

If you want the plugin to ignore certain cases.

**Comment by syrm-ll** [comment]
I misunderstood, the jar I checked in the IDE, I thought it had `Automatic-Module-Name`;
`failOnMissingModuleInfo.set(false)` does help.

![图片](https://github.com/gradlex-org/extra-java-module-info/assets/40515646/a487a840-d4d6-43ec-a001-72aa6d71b6c3)
![图片](https://github.com/gradlex-org/extra-java-module-info/assets/40515646/31fd9373-2f8d-4583-bfd7-7deb15743030)

> This is Gradle core behavior and nothing this plugin influences.

What I want to express is that gradle just can't recognize the jar without `module-info.class` or `Automatic-Module-Name`([although this is against the Java module specification](https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html#automatic-modules)
), but it will not prevent the dependency transfer, as long as you don't explicitly `requires` it, and it can work as an automatic module or as an unnamed module.

The plug-in prevents the transfer of dependencies by default. Even if you don't need explicit `requires`, you must declare it in `extraJavaModuleInfo`, otherwise it will not appear in the dependency list at all. When `gradle build`, it will appear like The error is as follows (When there is no `failOnMissingModuleInfo.set(false)`):

```log
Execution failed for task ':XXX:compileJava'.
> Could not resolve all files for configuration ':XXX:compileClasspath'.
   > Failed to transform kotlin-stdlib-common-1.8.21.jar (org.jetbrains.kotlin:kotlin-stdlib-common:1.8.21) to match attributes {artifactType=jar, javaModule=true, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for ExtraJavaModuleInfoTransform: C:\env\data\gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.8.21\d749cd5ae25da36d06e5028785038e24f9d37976\kotlin-stdlib-common-1.8.21.jar.
         > Not a module and no mapping defined: kotlin-stdlib-common-1.8.21.jar
```

Whether the goal of the plugin is to build fully modular applications, or to provide a patch to gradle's behavior of not supporting automatic module resolution from jar filenames, this default behavior is not easy to use. 
When `failOnMissingModuleInfo.set(true)`:
extreme cases require finding dozens of blocked passes Dependencies, and configure `extraJavaModuleInfo` one by one, even if you don't need to `requires` modules directly.
When `failOnMissingModuleInfo.set(false)`:
There are tons of this boring configuration 👇
```kts
extraJavaModuleInfo {
    automaticModule("A-1.0.jar", "A")
    automaticModule("B-1.0.jar", "B")
    automaticModule("C-1.0.jar", "C")
    // ...
}
```

Consider providing a switch that allows jars that don't have an explicit module name to be parsed directly from the filename? Like <https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html#automatic-modules> describes. Then allow explicitly declared `module` or `automaticModule` in `extraJavaModuleInfo` to override them.

So ideally we only need to enable this option, or directly as the default behavior of the plugin, we only need `org.gradlex.extra-java-module-info`, which can work without any additional configuration information
