### ISSUE TITLE
How can I transitively define extra module information?

### ISSUE THREAD

**Issue by arjenzhou** [gradlex-org/extra-java-module-info#63]
There is a project A has module `module com.arjenzhou.kit.scheduler`, defined as
```kotlin
val quartzVersion = project.property("quertz.version")

dependencies {
    implementation("org.quartz-scheduler:quartz:${quartzVersion}")
}

plugins {
    id("org.gradlex.extra-java-module-info")
}

extraJavaModuleInfo {
    // quartz has not supported JPMS yet
    module("quartz-${quartzVersion}.jar", "org.quartz", "$quartzVersion") {
        requires("org.slf4j")
        requires("java.desktop")
        requires("java.rmi")
        exportAllPackages()
    }
    // quartz related dependencies, whose versions are depend on quartz, not globally used.
    module("HikariCP-java7-2.4.13.jar", "hikari", "2.4.13")
    module("c3p0-0.9.5.4.jar", "c3p0", "0.9.5.4")
    module("mchange-commons-java-0.2.15.jar", "mchange.commons.java", "0.2.15")
}
```

And project B implements A, uses module `com.arjenzhou.kit.scheduler`

```java
module com.arjenzhou.kit.scheduler {
    requires org.quartz;
    requires org.slf4j;

    exports com.arjenzhou.kit.scheduler;
    exports com.arjenzhou.kit.scheduler.job;
    exports com.arjenzhou.kit.scheduler.job.internal to
        org.quartz;

    uses com.arjenzhou.kit.scheduler.job.ScheduledJob;
}
```
And error occurs in project B: 
```
java.lang.module.FindException: Module org.quartz not found, required by com.arjenzhou.kit.scheduler
```

How can I let project B know module `org.quartz` defined in project A?

**Comment by jjohannes** [comment]
Hi @arjenzhou. From your description it sounds like you only use the plugin in project A. You should use it in all projects for the extra information to be available everywhere. Meaning, the `extraJavaModuleInfo { ... }` block needs to be in **all** projects.

The best thing to do that is to use _convention plugins_ for shared build configuration. 

Here is a small example with a convention plugin setup that includes `extra-java-module-info`:
https://github.com/gradlex-org/java-module-testing/tree/main/samples/use-all-java-module-plugins

**Comment by arjenzhou** [comment]
@jjohannes Thanks, I will try it out.
