### ISSUE TITLE
exportAllPackages() breaks module for multi-release jar packages

### ISSUE THREAD

**Issue by crschnick** [gradlex-org/extra-java-module-info#77]
I am using extra-java-module-info v1.5 to modularize the dependency `org.kohsuke:github-api:1.317`. When using `exportAllPackages()` it somehow breaks with an invalid module exception caused by a multi-release package being exported. So for now I export all packages manually and that works for me [like this](https://github.com/xpipe-io/xpipe/blob/579ad6f1ea21a9c1ea083fd596e6f5e665cc1f0f/app/gradle_scripts/github-api.gradle)

**Comment by jjohannes** [comment]
Thanks for reporting.
